version: '3.7'

services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: go run main.go
    restart: always
    ports:
      - "5000:5000"
    volumes: 
      - ./api/src:/go/src/app
    links:
      - db:db-dev
  swagger-ui:
    image: swaggerapi/swagger-ui
    restart: always
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ./doc/swagger.yaml:/swagger.yaml
    environment:
      SWAGGER_JSON: /swagger.yaml
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes: 
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: bancouat
      POSTGRES_USER: bancouat
      POSTGRES_PASSWORD: bancouat
  static:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    links:
      - app
    environment:
      - NGINX_PORT=80
  # migrate:
  #   image: migrate/migrate
  #   container_name: migrate
  #   command: ["-database", "postgres://bancouat:bancouat@db/bancouat?sslmode=disable", "-path", "/migrations", "up"]
  #   volumes:
  #     - ./api/migrations:/migrations
  #   depends_on:
  #     - db
  #   links: 
  #     - db
volumes:
  pgdata:
