version: '3.7'

services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: go run main.go
    ports:
      - "5000:5000"
    volumes: 
      - ./api/src:/go/src/app
    links:
      - db:db-dev
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes: 
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: bancouat
      POSTGRES_USER: bancouat
      POSTGRES_PASSWORD: bancouat

volumes:
  pgdata:
